application: PWSubmit
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: testscript.php

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /scripts
  static_dir: scripts
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /static
  static_dir: static
  


  